#!/usr/bin/env python3
# make_link_proof.py - build this session's bridge proof: one .docx + one .pptx
# plus deliverable/OFFICE_HASHES.json, the manifest the REAL machine verifies.
#
# Why it exists (session 01a0a9f0, 2026-09-16):
#   the user asked to install the git-sync skill from arena.ai/agent/01a0a98d
#   and to hook it up to their own Windows box (conda base, E:\0github\git-sync).
#   A link that is only claimed is worth nothing - the deliverables must travel
#   through git and be judged by the watcher on that machine. This script builds
#   them, and then re-implements code/local_check.ps1 section 3 (3a-3g) in
#   Python so the package can be proven INSIDE the sandbox before it is pushed.
#
# Sandbox policy (v2.8.0): python-docx / python-pptx / .venv are allowed here -
# they are just generators. The only hard rule left is that "local" means the
# user's machine: no local/inbox, no hand-made stand-in skill.
#
# Usage:
#   python3 code/make_link_proof.py            # build + self-verify + manifest
#   python3 code/make_link_proof.py --verify   # only re-run the 3a-3g mirror
#
# Exit codes: 0 ok, 1 a check failed (never write a manifest you cannot prove).

import hashlib
import json
import os
import re
import sys
import zipfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
OUT = os.path.join(ROOT, 'deliverable')
MANIFEST = os.path.join(OUT, 'OFFICE_HASHES.json')
DOCX = os.path.join(OUT, 'LINK_PROOF_v2.8.1.docx')
PPTX = os.path.join(OUT, 'LINK_PROOF_v2.8.1.pptx')

BRANCH_FALLBACK = 'arena/01a0a9f0-git-pull-arena'
MARKERS = ['2.8.1', 'git-sync', 'local_check.ps1', 'round 20']


# --------------------------------------------------------------------- facts
def repo_facts():
    facts = {'branch': BRANCH_FALLBACK, 'version': '2.8.1', 'host': '', 'lines': []}
    cfg = os.path.join(ROOT, 'skills', 'git-sync', 'sync.config.json')
    try:
        with open(cfg, encoding='utf-8-sig') as fh:
            facts['branch'] = json.load(fh).get('branch') or BRANCH_FALLBACK
    except Exception:
        pass
    ver = os.path.join(ROOT, 'skills', 'git-sync', 'VERSION')
    try:
        with open(ver, encoding='utf-8') as fh:
            facts['version'] = fh.read().strip() or facts['version']
    except Exception:
        pass
    hw = os.path.join(ROOT, 'results', 'hardware', 'latest.md')
    if os.path.isfile(hw):
        with open(hw, encoding='utf-8', errors='replace') as fh:
            text = fh.read()
        for line in text.splitlines():
            line = line.strip()
            if line.startswith('- generated:'):
                m = re.search(r'host:\s*([^\s]+)', line)
                if m:
                    facts['host'] = m.group(1)
            if line.startswith('- '):
                facts['lines'].append(line[2:])
    return facts


def hw_line(facts, needle):
    for line in facts['lines']:
        if line.lower().startswith(needle):
            return line
    return ''


# ---------------------------------------------------------------------- docx
def build_docx(facts):
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.core_properties.title = 'Local <-> Arena bridge proof'
    doc.core_properties.comments = 'git-sync v%s branch %s' % (facts['version'], facts['branch'])

    doc.add_heading('Local <-> Arena bridge proof', 0)
    doc.add_paragraph('git-sync v%s  |  branch %s  |  generated by code/make_link_proof.py'
                      % (facts['version'], facts['branch']))

    doc.add_heading('1. What this round installed', level=1)
    for line in [
        'skill: skills/git-sync v%s, installed by skills/git-sync/scripts/agent-install.sh '
        '(upgrade v2.7.4 -> v%s, source branch arena/01a0a98d-git-pull-arena)' % (facts['version'], facts['version']),
        'repo gate: code/check_all.sh (ASCII-only .ps1, config branch == HEAD, root scripts == skill scripts, '
        '$var: typo scan, watcher closing lines, .ps1 parse)',
        'real-machine check: code/local_check.ps1 - the script the watcher runs when the agent requests a check',
        'user side: a NEW clone (never overwrite an existing folder) + bootstrap.ps1 -Auto registers the watcher',
    ]:
        doc.add_paragraph(line, style='List Bullet')

    doc.add_heading('2. The loop (who does what)', level=1)
    table = doc.add_table(rows=1, cols=3)
    table.style = 'Table Grid'
    hdr = table.rows[0].cells
    for i, name in enumerate(['step', 'command', 'runs on']):
        hdr[i].text = name
    for row in [
        ('work + push', 'bash skills/git-sync/scripts/agent-sync.sh "feat: ..."', 'Arena sandbox'),
        ('request a check', 'bash skills/git-sync/scripts/agent-check.sh --request "verify ..."', 'Arena sandbox'),
        ('pull + run the check', 'sync.ps1  ->  code/local_check.ps1  ->  push verdict', 'user machine (watcher)'),
        ('read the verdict', 'bash skills/git-sync/scripts/agent-check.sh --read   (0 pass / 2 fail / 3 pending)', 'Arena sandbox'),
        ('close the loop', 'bash skills/git-sync/scripts/agent-check.sh --accept', 'Arena sandbox'),
    ]:
        cells = table.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = value

    doc.add_heading('3. What the real machine checks (code/local_check.ps1)', level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr = table.rows[0].cells
    hdr[0].text = 'item'
    hdr[1].text = 'what it proves'
    for item, what in [
        ('gate', 'the repo gate runs on this machine (git-bash), including the python-based scans'),
        ('3a', 'sha256 + byte size of every deliverable equal the copy the agent generated'),
        ('3b', 'all required OOXML parts are present (missing part = Office says the file is corrupt)'),
        ('3c', 'every .xml / .rels part parses'),
        ('3d', 'every relationship target resolves inside the package (no dangling r:id)'),
        ('3e', '[Content_Types].xml covers every part'),
        ('3f', 'the text markers are really in the document'),
        ('3g', 'the deck still has at least the promised number of slides'),
        ('3h', 'real Word / PowerPoint (or WPS) opens the file read-only, with a hard timeout'),
        ('2a-2d', 'silent push proven, watcher window class, closing lines, hands-free pull/push'),
    ]:
        cells = table.add_row().cells
        cells[0].text = item
        cells[1].text = what

    doc.add_heading('4. The machine on the other end', level=1)
    host = facts['host'] or 'LAPTOP-R77M5D6M'
    machine = [
        'host ' + host + ' (from results/hardware/latest.md, produced by hardware.ps1)',
        hw_line(facts, 'os:'),
        hw_line(facts, 'cpu:'),
        hw_line(facts, 'ram:'),
        hw_line(facts, 'nvidia'),
        hw_line(facts, 'global python:'),
        hw_line(facts, 'conda:'),
        hw_line(facts, 'git:'),
    ]
    for line in machine:
        if line:
            doc.add_paragraph(line, style='List Bullet')
    doc.add_paragraph(
        'v2.8.1 note: the gate now proves each python candidate (python3 / python / py -3) instead of trusting '
        'the name. On this machine the Microsoft Store stub answered "python3" and exited non-zero, so the '
        'python-based checks used to SKIP; with the conda base python on PATH they now really run.')

    doc.add_heading('5. How to read a verdict', level=1)
    for line in [
        'results/status/handshake.json - round, arena_state (awaiting_check / accepted) and local_state (passed / failed)',
        'results/status/check_rN_<timestamp>.txt - the full log the machine uploaded for round N',
    ]:
        doc.add_paragraph(line, style='List Bullet')

    doc.add_heading('6. Rules that do not bend', level=1)
    for line in [
        '"local" means the scheduled watcher task on the user Windows box - never a folder in the sandbox',
        'the sandbox may pip install and use .venv (v2.8.0): generators are tools, not evidence',
        'the sandbox never claims success on its own: the verdict has to come back through git',
    ]:
        doc.add_paragraph(line, style='List Bullet')

    doc.add_heading('7. 本机回执（round 20，已通过）', level=1)
    for line in [
        'round 20 在你本机（%s）判定：passed（exit 0，用时 21 秒）' % host,
        '3a-3g：两个产物的 sha256/字节、OOXML 必需部件、XML 解析、关系不断链、内容类型、标记词、页数（6 >= 6）全部 OK',
        '3h：真 Word.Application 只读打开 LINK_PROOF_v2.8.1.docx；真 PowerPoint.Application 只读打开 LINK_PROOF_v2.8.1.pptx（6 页）',
        '闸门：本机用真 PowerShell 解析器逐个解析 .ps1（沙箱只能 SKIP 这一步）',
        '完整日志：results/status/check_r20_20260916-192634.txt（本机推回本分支）',
    ]:
        doc.add_paragraph(line, style='List Bullet')

    doc.add_heading('8. 中文说明：这条链路怎么用', level=1)
    for line in [
        '链路：Arena 会话（沙箱）↔ 你的 Windows 本机，中间只有 git；本机侧就是一个计划任务值守。',
        '本机只做一次：新文件夹 clone → .\\bootstrap.ps1 -Auto（注册值守 + 配好免点击推送）。之后不用手动 sync/push。',
        '值守每 2 分钟一轮：自动 pull → 跑 code\\local_check.ps1 → 把 passed/failed 与完整日志推回本分支。',
        '取交付物：.\\download.ps1 -Set final（镜像到 ..\\<仓库名>_out\\），或直接打开本仓库的 deliverable 目录。',
        '看结论：results/status/handshake.json（round / arena_state / local_state）+ results/status/check_rN_*.txt（每轮日志）。',
        '切回本会话值守：cd E:\\0github\\git-sync\\git-pull-arena-01a0a9f0 ; .\\watch.ps1 -Focus；恢复其他会话：.\\watch.ps1 -RestoreParked。',
    ]:
        doc.add_paragraph(line, style='List Bullet')

    doc.add_paragraph()
    doc.add_paragraph('markers: ' + ' , '.join(MARKERS + [host, facts['branch']]))
    doc.save(DOCX)


# ---------------------------------------------------------------------- pptx
def build_pptx(facts):
    from pptx import Presentation
    from pptx.util import Pt

    host = facts['host'] or 'LAPTOP-R77M5D6M'
    prs = Presentation()

    def bullets(slide, items):
        frame = slide.placeholders[1].text_frame
        frame.clear()
        for i, item in enumerate(items):
            para = frame.paragraphs[0] if i == 0 else frame.add_paragraph()
            para.text = item
            para.font.size = Pt(16)

    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = 'Local <-> Arena bridge proof'
    slide.placeholders[1].text = 'git-sync v%s  |  branch %s' % (facts['version'], facts['branch'])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'What was installed'
    bullets(slide, [
        'skill git-sync v%s (source branch arena/01a0a98d-git-pull-arena)' % facts['version'],
        'upgrade path v2.7.4 -> v%s, installer refuses to downgrade' % facts['version'],
        'repo gate code/check_all.sh + real-machine check code/local_check.ps1',
        'python-docx / python-pptx are allowed in the sandbox (v2.8.0 policy)',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'The loop'
    bullets(slide, [
        'Arena: agent-sync.sh pushes the work to the branch',
        'Arena: agent-check.sh --request asks for a check (round + 1)',
        'machine: the watcher pulls, runs local_check.ps1, pushes the verdict',
        'Arena: --read the verdict (0 pass / 2 fail / 3 pending), then --accept',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'What the machine proves'
    bullets(slide, [
        '3a sha256 + bytes  |  3b required OOXML parts  |  3c every XML part parses',
        '3d every relationship resolves  |  3e content types cover every part',
        '3f text markers present  |  3g slide count kept',
        '3h real Word / PowerPoint opens the file read-only',
        '2a-2d silent push, watcher window class, closing lines, hands-free',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'The other end'
    bullets(slide, [
        'host ' + host + ' - Windows 11, i5-10200H, 15.9 GB RAM',
        'GPU NVIDIA GeForce GTX 1650 4 GB - Office COM available',
        'conda base python 3.11.9 (E:\\spider\\python.exe) - used by the local checks',
        'v2.8.1 gate probes python3 / python / py -3, so the checks stop SKIPping',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'Verdict and receipt'
    bullets(slide, [
        'results/status/handshake.json: round, arena_state, local_state',
        'results/status/check_rN_<timestamp>.txt: the full log of that round',
        'passed -> agent-check.sh --accept closes the loop',
        'no fake local side: no local/inbox, no stand-in skill',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = '本机回执 / machine receipt (round 20)'
    bullets(slide, [
        'round 20 在 %s 判定 passed（exit 0，21 秒）' % host,
        '3a-3g 全 OK：哈希/字节、必需部件、XML、关系、内容类型、标记词、页数 6 >= 6',
        '3h：真 Word 只读打开 .docx；真 PowerPoint 只读打开 .pptx（6 页）',
        '本机还跑了真 PowerShell 解析器逐个解析 .ps1（沙箱只能 SKIP）',
    ])

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = '中文说明：这条链路怎么用'
    bullets(slide, [
        '链路：Arena 会话（沙箱）↔ 你的 Windows 本机，中间只有 git',
        '本机只做一次：clone 新文件夹 → .\\bootstrap.ps1 -Auto（注册值守 + 免点击推送）',
        '值守每 2 分钟：自动 pull → 跑 code\\local_check.ps1 → 把结论和日志推回分支',
        '取产物：.\\download.ps1 -Set final；看结论：results/status/handshake.json 与 check_rN_*.txt',
    ])

    prs.save(PPTX)


# --------------------------------------------------- mirror of local_check 3a-3g
def rels_base(name):
    segs = name.split('/')
    return '/'.join(segs[:-2]) if len(segs) > 2 else ''


def resolve(base, target):
    segs = [s for s in base.split('/') if s] if base else []
    for part in target.split('/'):
        if part in ('', '.'):
            continue
        if part == '..':
            segs = segs[:-1] if len(segs) > 1 else []
            continue
        segs.append(part)
    return '/'.join(segs)


def verify(manifest):
    problems = []
    for entry in manifest['files']:
        rel = entry['path']
        path = os.path.join(ROOT, rel.replace('/', os.sep))
        if not os.path.isfile(path):
            problems.append('MISSING ' + rel)
            continue
        raw = open(path, 'rb').read()
        if len(raw) != int(entry['bytes']):
            problems.append('SIZE %s expected %s got %d' % (rel, entry['bytes'], len(raw)))
        digest = hashlib.sha256(raw).hexdigest()
        if digest != entry['sha256']:
            problems.append('SHA256 ' + rel)

        with zipfile.ZipFile(path) as zf:
            names = zf.namelist()
            if len(set(names)) != len(names):
                problems.append('3b duplicate zip entries in ' + rel)
            name_set = set(names)

            missing = [p for p in entry['required_parts'] if p not in name_set]
            if missing:
                problems.append('3b missing parts in %s: %s' % (rel, ', '.join(missing)))

            xml_text = {}
            for name in names:
                if not name.endswith(('.xml', '.rels')):
                    continue
                try:
                    xml_text[name] = zf.read(name).decode('utf-8')
                except Exception as exc:
                    problems.append('3c unreadable %s in %s (%s)' % (name, rel, exc))
            import xml.etree.ElementTree as ET
            for name, text in xml_text.items():
                try:
                    ET.fromstring(text)
                except Exception:
                    problems.append('3c unparseable XML %s in %s' % (name, rel))

            for name, text in xml_text.items():
                if not name.endswith('.rels'):
                    continue
                base = rels_base(name)
                try:
                    root = ET.fromstring(text)
                except Exception:
                    continue
                for node in root:
                    target = node.get('Target') or ''
                    if not target or target.startswith('http'):
                        continue
                    if resolve(base, target) not in name_set:
                        problems.append('3d dangling %s -> %s in %s' % (name, target, rel))

            ct = xml_text.get('[Content_Types].xml')
            if ct is None:
                problems.append('3e no [Content_Types].xml in ' + rel)
            else:
                root = ET.fromstring(ct)
                defs = set()
                ovrs = set()
                for node in root:
                    tag = node.tag.split('}')[-1]
                    if tag == 'Default':
                        defs.add((node.get('Extension') or '').lower())
                    elif tag == 'Override':
                        ovrs.add(node.get('PartName') or '')
                for name in names:
                    if name == '[Content_Types].xml':
                        continue
                    ext = name.rsplit('.', 1)[-1].lower() if '.' in name else ''
                    if ('/' + name) not in ovrs and ext not in defs:
                        problems.append('3e no content type for %s in %s' % (name, rel))

            body = ''.join(xml_text.values())
            for marker in entry['must_contain']:
                if marker not in body:
                    problems.append('3f marker %r not found in %s' % (marker, rel))

            if entry.get('min_slides'):
                slides = len([n for n in names if re.match(r'^ppt/slides/slide[0-9]+\.xml$', n)])
                if slides < int(entry['min_slides']):
                    problems.append('3g slides %d < %d in %s' % (slides, entry['min_slides'], rel))
            if entry.get('main_part') and entry['main_part'] not in name_set:
                problems.append('main_part %s not in %s' % (entry['main_part'], rel))
    return problems


def main():
    verify_only = '--verify' in sys.argv[1:]
    facts = repo_facts()
    os.makedirs(OUT, exist_ok=True)

    if not verify_only:
        build_docx(facts)
        build_pptx(facts)
        print('built: %s' % os.path.relpath(DOCX, ROOT))
        print('built: %s' % os.path.relpath(PPTX, ROOT))
    elif not (os.path.isfile(DOCX) and os.path.isfile(PPTX)):
        print('[ERROR] nothing to verify - run without --verify first', file=sys.stderr)
        return 1

    entries = []
    for path, kind, required, main_part, markers, min_slides in [
        (DOCX, 'docx', ['[Content_Types].xml', '_rels/.rels', 'word/document.xml', 'word/styles.xml',
                        'word/_rels/document.xml.rels', 'docProps/core.xml'], 'word/document.xml',
         MARKERS + [facts['host'], facts['branch']], None),
        (PPTX, 'pptx', ['[Content_Types].xml', '_rels/.rels', 'ppt/presentation.xml',
                        'ppt/_rels/presentation.xml.rels', 'ppt/slides/slide1.xml',
                        'ppt/slideMasters/slideMaster1.xml', 'ppt/slideLayouts/slideLayout1.xml',
                        'ppt/theme/theme1.xml', 'docProps/core.xml'], 'ppt/presentation.xml',
         MARKERS + [facts['host'], facts['branch']], 8),
    ]:
        if verify_only and os.path.isfile(MANIFEST):
            with open(MANIFEST, encoding='utf-8') as fh:
                cached = json.load(fh)
            for item in cached.get('files', []):
                if item['path'] == os.path.relpath(path, ROOT).replace(os.sep, '/'):
                    entries.append(item)
                    break
            else:
                pass
        if any(e['path'] == os.path.relpath(path, ROOT).replace(os.sep, '/') for e in entries):
            continue
        raw = open(path, 'rb').read()
        with zipfile.ZipFile(path) as zf:
            present = set(zf.namelist())
            slides = len([n for n in present if re.match(r'^ppt/slides/slide[0-9]+\.xml$', n)])
        entries.append({
            'path': os.path.relpath(path, ROOT).replace(os.sep, '/'),
            'kind': kind,
            'bytes': len(raw),
            'sha256': hashlib.sha256(raw).hexdigest(),
            'required_parts': required,
            'main_part': main_part,
            'must_contain': [m for m in markers if m],
            'min_slides': min_slides,
            'sandbox_selftest': {'parts': len(present), 'slides': slides},
        })

    manifest = {
        'generated_utc': None,
        'generator': 'code/make_link_proof.py',
        'generator_note': ('python-docx + python-pptx (allowed in the sandbox since v2.8.0); the manifest is the '
                           'contract the REAL machine verifies in code/local_check.ps1 section 3, and the same '
                           '3a-3g rules are mirrored in Python here so a package that cannot pass is never pushed'),
        'branch': facts['branch'],
        'skill_version': facts['version'],
        'how_local_verifies': ('code/local_check.ps1 compares sha256/bytes, opens the package, requires every '
                               'required_parts entry, parses every .xml/.rels part, resolves every relationship '
                               'target and content type, searches must_contain across all xml parts and counts '
                               'slides against min_slides; the Office COM open test (3h) runs on the real machine'),
        'files': entries,
    }
    import datetime
    manifest['generated_utc'] = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

    problems = verify(manifest)
    if problems:
        print('[FAIL] the 3a-3g mirror found %d problem(s) - manifest NOT written:' % len(problems), file=sys.stderr)
        for item in problems:
            print('       ' + item, file=sys.stderr)
        return 1

    if not verify_only:
        with open(MANIFEST, 'w', encoding='utf-8') as fh:
            json.dump(manifest, fh, ensure_ascii=False, indent=2)
            fh.write('\n')
        print('wrote: %s' % os.path.relpath(MANIFEST, ROOT))

    print('== 3a-3g mirror PASSED for %d file(s)' % len(entries))
    for entry in entries:
        print('   OK %s (%d B, %s, slides=%s)'
              % (entry['path'], entry['bytes'], entry['kind'], entry['sandbox_selftest']['slides']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
